import type { BuildStats } from './pipeline';

export interface TownStats {
  name: string;
  stats: BuildStats;
}

const pct = (n: number, total: number) => (total ? `${((n / total) * 100).toFixed(1)}%` : '–');

/** Markdown classification report: counts per category and the most common unmapped tag combinations. */
export function renderReport(towns: TownStats[], top = 30): string {
  const lines: string[] = [
    '# Classification report',
    '',
    'Generated by `toytown build-data`. Regenerate with `pnpm data:build`.',
    '',
    'Buildings are classified with `assets/models/tag-map.json` (see `docs/tag-mapping.md`).',
    '"Unmapped" means no rule, POI or heuristic matched, so the building fell back to `generic`.',
    '',
    '## Summary',
    '',
    `| | ${towns.map((t) => t.name).join(' | ')} |`,
    `| --- | ${towns.map(() => '---:').join(' | ')} |`,
  ];
  const row = (label: string, f: (s: BuildStats) => string) =>
    lines.push(`| ${label} | ${towns.map((t) => f(t.stats)).join(' | ')} |`);
  row('bbox (w,s,e,n)', (s) => `\`${s.bbox.join(',')}\``);
  row('OSM data as of', (s) => s.osm_timestamp ?? '–');
  row('Buildings', (s) => String(s.buildings));
  for (const v of ['landmark', 'tags', 'poi', 'heuristic', 'fallback']) {
    row(`… classified by ${v}`, (s) => `${s.via[v] ?? 0} (${pct(s.via[v] ?? 0, s.buildings)})`);
  }
  row(
    'Buildings with a street-facing front',
    (s) => `${s.withFront} (${pct(s.withFront, s.buildings)})`,
  );
  row('POIs inside buildings', (s) => String(s.pois.inBuildings));
  row('Standalone POI points', (s) => String(s.pois.standalone));
  row('Trees (mapped + scattered)', (s) => `${s.trees.osm} + ${s.trees.scattered}`);

  const cats = [...new Set(towns.flatMap((t) => Object.keys(t.stats.categories)))].sort(
    (a, b) =>
      towns.reduce((n, t) => n + (t.stats.categories[b] ?? 0), 0) -
        towns.reduce((n, t) => n + (t.stats.categories[a] ?? 0), 0) || (a < b ? -1 : 1),
  );
  lines.push(
    '',
    '## Buildings per category',
    '',
    `| Category | ${towns.map((t) => t.name).join(' | ')} |`,
  );
  lines.push(`| --- | ${towns.map(() => '---:').join(' | ')} |`);
  for (const c of cats) {
    lines.push(
      `| \`${c}\` | ${towns.map((t) => { const n = t.stats.categories[c] ?? 0; return n ? `${n} (${pct(n, t.stats.buildings)})` : '–'; }).join(' | ')} |`, // prettier-ignore
    );
  }

  for (const t of towns) {
    lines.push('', `## ${t.name}: top ${top} unmapped tag combinations`, '');
    const u = t.stats.unmapped.slice(0, top);
    if (!u.length) {
      lines.push('None.');
      continue;
    }
    lines.push('| # | Tags | Buildings |', '| ---: | --- | ---: |');
    u.forEach((x, i) =>
      lines.push(`| ${i + 1} | \`${x.tags.replaceAll('|', '\\|')}\` | ${x.count} |`),
    );
  }
  lines.push('');
  return lines.join('\n');
}
